spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/incidentdb
spring.datasource.username=student
spring.datasource.password=student123

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=notification-group

spring.kafka.consumer.auto-offset-reset=earliest

server.port=9099
